---
api: 2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core: "8.x"

defaults:
  projects:
    subdir: "contrib"

projects:

  # Core.
  drupal:
    version: 8.1
    # Use this if you need a working git repository of Drupal core instead of
    # the latest stable.
    # type: "core"
    # download:
    #   # Drupal core branch (e.g. "6.x", "7.x", "8.0.x").
    #   branch: "8.1.x"
    #   working-copy: true

  # Other modules.
  devel: "1.x-dev"
  redis:
    download:
      type: git
      url: https://github.com/md-systems/redis.git
      branch: 8.x-1.x
  migrate_upgrade: "2.0-beta1"
  migrate_plus: "2.0-beta1"
  migrate_tools: "2.0-beta1"
  migrate_manifest: "1.2"
  config_devel: "1.0-rc1"
